name: ServiceNow CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 🔍 Probe NOW_SOURCE_INSTANCE
      run: |
          if [ -z "$NOW_SOURCE_INSTANCE" ]; then
          echo "❌ NOW_SOURCE_INSTANCE is NOT set"
          exit 1
          fi
          echo "✅ NOW_SOURCE_INSTANCE length: ${#NOW_SOURCE_INSTANCE}"
          echo "✅ NOW_SOURCE_INSTANCE prefix: ${NOW_SOURCE_INSTANCE:0:3}***"
          nslookup "$NOW_SOURCE_INSTANCE" || true    # DNS test

    # 1. Apply current branch to your DEV instance
    - name: Apply changes to DEV
      uses: ServiceNow/sncicd-apply-changes@2.0.0
      env:
        nowUsername: ${{ secrets.NOW_USERNAME }}
        nowPassword: ${{ secrets.NOW_PASSWORD }}
        nowSourceInstance: ${{ secrets.NOW_SOURCE_INSTANCE }}
        appSysID: ${{ secrets.APP_SYS_ID }}

    
