name: ServiceNow CI/CD  (hard-coded demo)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  dev-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Apply changes to DEV
        uses: ServiceNow/sncicd-apply-changes@2.0.0
        env:
          nowUsername:       "gitHubUser"
          nowPassword:       "Password@123"
          nowSourceInstance: "dev296293.service-now.com"
          appSysID:          "474f90ddc38ae6107152d8ec050131b5"

      - name: Publish app
        id: publish
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: "1.${{ github.run_number }}"
          versionFormat: template
        env:
          nowUsername:       "gitHubUser"
          nowPassword:       "Password@123"
          nowSourceInstance: "dev296293.service-now.com"
          appSysID:          "474f90ddc38ae6107152d8ec050131b5"

  test-deploy:
    needs: dev-build
    runs-on: ubuntu-latest
    steps:
      - name: Install app on TEST
        uses: ServiceNow/sncicd-install-app@2.0.0
        with:
          version: ${{ needs.dev-build.outputs.publish_newVersion }}
        env:
          nowUsername:       "gitHubUser"
          nowPassword:       "Password@123"
          nowInstallInstance: "dev296293.service-now.com"      
          appSysID:          "474f90ddc38ae6107152d8ec050131b5"
