name: ServiceNow CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dev-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Echo instance name for sanity
      run: echo "$NOW_SOURCE_INSTANCE"

    # 1. Apply current branch to your DEV instance
    - name: Apply changes to DEV
      uses: ServiceNow/sncicd-apply-changes@2.0.0
      env:
        nowUsername: ${{ secrets.NOW_USERNAME }}
        nowPassword: ${{ secrets.NOW_PASSWORD }}
        nowSourceInstance: ${{ secrets.NOW_SOURCE_INSTANCE }}
        appSysID: ${{ secrets.APP_SYS_ID }}

    # 2. (Optional) run ATF here with sncicd-run-ATF

    # 3. Publish the app to the App Repo
    - name: Publish app
      id: publish
      uses: ServiceNow/sncicd-publish-app@2.0.1
      with:
        versionTemplate: "1.${{ github.run_number }}"
        versionFormat: template
      env:
        nowUsername: ${{ secrets.NOW_USERNAME }}
        nowPassword: ${{ secrets.NOW_PASSWORD }}
        nowSourceInstance: ${{ secrets.NOW_SOURCE_INSTANCE }}
        appSysID: ${{ secrets.APP_SYS_ID }}

  test-deploy:
    needs: dev-build
    runs-on: ubuntu-latest
    steps:
    - name: Wait / create Change (optional)
      uses: ServiceNow/servicenow-devops-change@v6
      if: success()
      with:
        devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        context-github: ${{ toJSON(github) }}
        job-name: Deploy to TEST

    # 4. Install the freshly-published version on TEST
    - name: Install app on TEST
      uses: ServiceNow/sncicd-install-app@v2.0.0
      with:
        version: ${{ needs.dev-build.outputs.publish_newVersion }}
      env:
        nowUsername: ${{ secrets.NOW_USERNAME }}
        nowPassword: ${{ secrets.NOW_PASSWORD }}
        nowInstallInstance: ${{ secrets.NOW_INSTALL_INSTANCE }}
        appSysID: ${{ secrets.APP_SYS_ID }}
